version:              '3.3'

services:
  web:
    image:            retool/core
    build:            https://github.com/retool-solutions/core.git
    ports:
      - 80:80
      - 443:443
    configs:
      - source:       default.conf
        target:       /etc/nginx/conf.d/default.conf
    volumes:
      - ./code:/usr/share/nginx/html:ro
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    command:          nginx-debug -g 'daemon off;'
    deploy:
      replicas:       2
      restart_policy:
        condition:    on-failure
configs:
  default.conf:
    external:         true
